#!/usr/bin/env python3
"""Regenerate include/novasvg/detail/default_font.h from data/fonts/DejaVuSans.ttf.

The header embeds a Latin subset of DejaVu Sans as base64, used by novasvg only as the last-resort
fallback when the machine has no font for a request (see FontFaceCache::getFontFace). Kerning
(GPOS and the legacy kern table) and the ligature substitutions are kept so that text lays out exactly
like the full font; test_novasvg_embedded_font checks that.

    python tools/gen_default_font.py            # needs: pip install fonttools

The base64 is split into literals well under MSVC's per-literal limit (16380 characters).
"""
import base64
import io
import sys
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "fonts" / "DejaVuSans.ttf"
TARGET = ROOT / "include" / "novasvg" / "detail" / "default_font.h"
CHUNK = 12000

# Basic Latin, Latin-1 Supplement, the punctuation/symbols text commonly carries, and the f-ligature
# presentation forms U+FB00..FB04 (novasvg applies the font's fi/fl/ff/ffi/ffl ligatures through them).
CODEPOINTS = (
    list(range(0x20, 0x7F))
    + list(range(0xA0, 0x100))
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x20AC, 0x2122]
    + list(range(0xFB00, 0xFB05))
)
FEATURES = ["kern", "liga", "calt", "ccmp", "locl", "mark", "mkmk", "clig"]


def subset_font():
    options = subset.Options()
    options.layout_features = FEATURES
    options.legacy_kern = True
    options.hinting = False
    options.notdef_outline = True
    options.name_IDs = ["*"]
    font = TTFont(str(SOURCE))
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=CODEPOINTS)
    subsetter.subset(font)
    out = io.BytesIO()
    font.save(out)
    return out.getvalue()


def render(data):
    encoded = base64.b64encode(data).decode("ascii")
    chunks = [encoded[i:i + CHUNK] for i in range(0, len(encoded), CHUNK)]
    lines = [
        "// Generated by tools/gen_default_font.py from data/fonts/DejaVuSans.ttf -- do not edit.",
        "//",
        "// A Latin subset of DejaVu Sans (%d bytes, base64 below), kerning and ligatures kept. It is" % len(data),
        "// novasvg's last-resort fallback font, registered only when a request finds no other font.",
        "// DejaVu fonts are free software: see data/fonts/LICENSE-DejaVu.txt.",
        "#pragma once",
        "",
        "namespace novasvg {",
        "namespace detail {",
        "",
        "// Split into literals under MSVC's 16380-character limit per string literal.",
        "inline constexpr const char* const kEmbeddedFontBase64[] = {",
    ]
    lines += ['    "%s",' % chunk for chunk in chunks]
    lines += ["    nullptr,", "};", "", "} // namespace detail", "} // namespace novasvg", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    data = subset_font()
    TARGET.write_text(render(data), newline="\n")
    print("wrote %s (%d font bytes)" % (TARGET.relative_to(ROOT), len(data)))
    sys.exit(0)
